name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
      - name: Install Deps (immutable)
        run: pnpm install --no-frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Verify build
        run: |
          test -f "dist/og_maker/index.js" || exit 1
          test -d "dist/client" || exit 1
          echo "✅ Build successful"
